"""add avatar_url to users

Revision ID: 8cd342be95fd
Revises: 
Create Date: 2026-04-07 19:14:51.311406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cd342be95fd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_alert_events_user_id'), table_name='alert_events')
    op.create_index(op.f('ix_alert_events_id'), 'alert_events', ['id'], unique=False)
    op.drop_constraint(op.f('alert_events_user_id_fkey'), 'alert_events', type_='foreignkey')
    op.create_foreign_key(None, 'alert_events', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('idx_alert_recipients_alert_id'), table_name='alert_recipients')
    op.create_index(op.f('ix_alert_recipients_id'), 'alert_recipients', ['id'], unique=False)
    op.drop_constraint(op.f('alert_recipients_recipient_id_fkey'), 'alert_recipients', type_='foreignkey')
    op.drop_constraint(op.f('alert_recipients_alert_id_fkey'), 'alert_recipients', type_='foreignkey')
    op.create_foreign_key(None, 'alert_recipients', 'users', ['recipient_id'], ['id'])
    op.create_foreign_key(None, 'alert_recipients', 'alert_events', ['alert_id'], ['id'])
    op.drop_index(op.f('idx_care_messages_recipient_id'), table_name='care_messages')
    op.drop_index(op.f('idx_care_messages_sender_id'), table_name='care_messages')
    op.create_index(op.f('ix_care_messages_id'), 'care_messages', ['id'], unique=False)
    op.drop_constraint(op.f('care_messages_recipient_id_fkey'), 'care_messages', type_='foreignkey')
    op.drop_constraint(op.f('care_messages_sender_id_fkey'), 'care_messages', type_='foreignkey')
    op.create_foreign_key(None, 'care_messages', 'users', ['recipient_id'], ['id'])
    op.create_foreign_key(None, 'care_messages', 'users', ['sender_id'], ['id'])
    op.drop_index(op.f('idx_energy_snapshots_user_id'), table_name='energy_snapshots')
    op.create_index(op.f('ix_energy_snapshots_id'), 'energy_snapshots', ['id'], unique=False)
    op.drop_constraint(op.f('energy_snapshots_user_id_fkey'), 'energy_snapshots', type_='foreignkey')
    op.create_foreign_key(None, 'energy_snapshots', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('idx_manual_charge_records_user_id'), table_name='manual_charge_records')
    op.create_index(op.f('ix_manual_charge_records_id'), 'manual_charge_records', ['id'], unique=False)
    op.drop_constraint(op.f('manual_charge_records_user_id_fkey'), 'manual_charge_records', type_='foreignkey')
    op.create_foreign_key(None, 'manual_charge_records', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('idx_signal_feature_daily_user_id'), table_name='signal_feature_daily')
    op.create_index(op.f('ix_signal_feature_daily_id'), 'signal_feature_daily', ['id'], unique=False)
    op.drop_constraint(op.f('signal_feature_daily_user_id_fkey'), 'signal_feature_daily', type_='foreignkey')
    op.create_foreign_key(None, 'signal_feature_daily', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('idx_user_auth_identities_user_id'), table_name='user_auth_identities')
    op.create_index(op.f('ix_user_auth_identities_id'), 'user_auth_identities', ['id'], unique=False)
    op.drop_constraint(op.f('user_auth_identities_user_id_fkey'), 'user_auth_identities', type_='foreignkey')
    op.create_foreign_key(None, 'user_auth_identities', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('idx_user_settings_user_id'), table_name='user_settings')
    op.create_index(op.f('ix_user_settings_id'), 'user_settings', ['id'], unique=False)
    op.drop_constraint(op.f('user_settings_user_id_fkey'), 'user_settings', type_='foreignkey')
    op.create_foreign_key(None, 'user_settings', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('avatar_url', sa.String(), nullable=True))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_index(op.f('idx_users_username'), table_name='users')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_index(op.f('idx_watcher_relations_target_id'), table_name='watcher_relations')
    op.drop_index(op.f('idx_watcher_relations_watcher_id'), table_name='watcher_relations')
    op.create_index(op.f('ix_watcher_relations_id'), 'watcher_relations', ['id'], unique=False)
    op.drop_constraint(op.f('watcher_relations_target_id_fkey'), 'watcher_relations', type_='foreignkey')
    op.drop_constraint(op.f('watcher_relations_watcher_id_fkey'), 'watcher_relations', type_='foreignkey')
    op.create_foreign_key(None, 'watcher_relations', 'users', ['target_id'], ['id'])
    op.create_foreign_key(None, 'watcher_relations', 'users', ['watcher_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'watcher_relations', type_='foreignkey')
    op.drop_constraint(None, 'watcher_relations', type_='foreignkey')
    op.create_foreign_key(op.f('watcher_relations_watcher_id_fkey'), 'watcher_relations', 'users', ['watcher_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('watcher_relations_target_id_fkey'), 'watcher_relations', 'users', ['target_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_watcher_relations_id'), table_name='watcher_relations')
    op.create_index(op.f('idx_watcher_relations_watcher_id'), 'watcher_relations', ['watcher_id'], unique=False)
    op.create_index(op.f('idx_watcher_relations_target_id'), 'watcher_relations', ['target_id'], unique=False)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_username'), 'users', ['username'], unique=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('users', 'avatar_url')
    op.drop_constraint(None, 'user_settings', type_='foreignkey')
    op.create_foreign_key(op.f('user_settings_user_id_fkey'), 'user_settings', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_user_settings_id'), table_name='user_settings')
    op.create_index(op.f('idx_user_settings_user_id'), 'user_settings', ['user_id'], unique=False)
    op.drop_constraint(None, 'user_auth_identities', type_='foreignkey')
    op.create_foreign_key(op.f('user_auth_identities_user_id_fkey'), 'user_auth_identities', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_user_auth_identities_id'), table_name='user_auth_identities')
    op.create_index(op.f('idx_user_auth_identities_user_id'), 'user_auth_identities', ['user_id'], unique=False)
    op.drop_constraint(None, 'signal_feature_daily', type_='foreignkey')
    op.create_foreign_key(op.f('signal_feature_daily_user_id_fkey'), 'signal_feature_daily', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_signal_feature_daily_id'), table_name='signal_feature_daily')
    op.create_index(op.f('idx_signal_feature_daily_user_id'), 'signal_feature_daily', ['user_id'], unique=False)
    op.drop_constraint(None, 'manual_charge_records', type_='foreignkey')
    op.create_foreign_key(op.f('manual_charge_records_user_id_fkey'), 'manual_charge_records', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_manual_charge_records_id'), table_name='manual_charge_records')
    op.create_index(op.f('idx_manual_charge_records_user_id'), 'manual_charge_records', ['user_id'], unique=False)
    op.drop_constraint(None, 'energy_snapshots', type_='foreignkey')
    op.create_foreign_key(op.f('energy_snapshots_user_id_fkey'), 'energy_snapshots', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_energy_snapshots_id'), table_name='energy_snapshots')
    op.create_index(op.f('idx_energy_snapshots_user_id'), 'energy_snapshots', ['user_id'], unique=False)
    op.drop_constraint(None, 'care_messages', type_='foreignkey')
    op.drop_constraint(None, 'care_messages', type_='foreignkey')
    op.create_foreign_key(op.f('care_messages_sender_id_fkey'), 'care_messages', 'users', ['sender_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('care_messages_recipient_id_fkey'), 'care_messages', 'users', ['recipient_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_care_messages_id'), table_name='care_messages')
    op.create_index(op.f('idx_care_messages_sender_id'), 'care_messages', ['sender_id'], unique=False)
    op.create_index(op.f('idx_care_messages_recipient_id'), 'care_messages', ['recipient_id'], unique=False)
    op.drop_constraint(None, 'alert_recipients', type_='foreignkey')
    op.drop_constraint(None, 'alert_recipients', type_='foreignkey')
    op.create_foreign_key(op.f('alert_recipients_alert_id_fkey'), 'alert_recipients', 'alert_events', ['alert_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('alert_recipients_recipient_id_fkey'), 'alert_recipients', 'users', ['recipient_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_alert_recipients_id'), table_name='alert_recipients')
    op.create_index(op.f('idx_alert_recipients_alert_id'), 'alert_recipients', ['alert_id'], unique=False)
    op.drop_constraint(None, 'alert_events', type_='foreignkey')
    op.create_foreign_key(op.f('alert_events_user_id_fkey'), 'alert_events', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_alert_events_id'), table_name='alert_events')
    op.create_index(op.f('idx_alert_events_user_id'), 'alert_events', ['user_id'], unique=False)
    # ### end Alembic commands ###
